from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from topoanalyzer.model.system import System


class BookSimUnsupportedError(ValueError):
    pass


@dataclass(frozen=True)
class BookSimOptions:
    traffic: str
    injection_rate: float
    injection_rate_unit: str = "packets/node/cycle"
    packet_size: int = 1
    warmup_cycles: int = 10000
    sample_cycles: int = 50000
    max_samples: int = 10
    num_vcs: int = 2
    vc_buffer_size: int = 8
    router_latency: int = 1


class BookSimConfigGenerator:
    def __init__(self, backend: str = "anynet_table") -> None:
        self.backend = _normalize_backend(backend)

    def generate(
        self,
        system: System,
        options: BookSimOptions,
        *,
        network_file: str | Path | None = None,
        route_table_file: str | Path | None = None,
    ) -> str:
        backend = self.resolved_backend(system)
        if backend == "stock_mesh":
            return self.generate_stock_mesh(system, options)
        if backend == "stock_fattree":
            return self.generate_stock_fattree(system, options)
        if backend == "anynet_runtime":
            return self.generate_anynet_runtime(
                system,
                options,
                network_file=network_file or "anynet.net",
            )
        return self.generate_anynet_table(
            system,
            options,
            network_file=network_file or "anynet.net",
            route_table_file=route_table_file or "anynet.routes",
        )

    def resolved_backend(self, system: System) -> str:
        if self.backend != "auto":
            return self.backend
        runtime = system.routing_table.metadata.get("booksim_runtime_routing")
        if isinstance(runtime, dict) and runtime.get("backend") == "stock_fattree":
            return "stock_fattree"
        if isinstance(runtime, dict) and runtime.get("backend") in {
            "anynet_runtime",
            "ubmesh_apr_runtime",
        }:
            return "anynet_runtime"
        return "anynet_table"

    def generate_anynet_table(
        self,
        system: System,
        options: BookSimOptions,
        *,
        network_file: str | Path,
        route_table_file: str | Path,
    ) -> str:
        if system.routing_table.metadata.get("booksim_runtime_routing"):
            raise BookSimUnsupportedError(
                f"routing table {system.routing_table.name!r} requires a BookSim "
                "runtime routing function; use booksim.backend: auto, stock_fattree, "
                "or anynet_runtime"
            )
        report = system.validate()
        report.raise_if_errors()
        bandwidths = sorted({link.bandwidth for link in system.graph.links})
        return "\n".join(
            [
                "// Generated by Topology Analyzer.",
                "// Backend: anynet_table.",
                "// Requires the Topology-Analyzer BookSim anynet route-table overlay.",
                f"// system = {system.name}",
                f"// topology_type = {system.topology_type}",
                f"// routing_table = {system.routing_table.name}",
                f"// modeled_link_bandwidths = {','.join(bandwidths)}",
                "topology = anynet;",
                "routing_function = min;",
                f"network_file = {_config_path(network_file)};",
                f"route_table_file = {_config_path(route_table_file)};",
                *self._common_options(options),
                "",
            ]
        )

    def generate_anynet_runtime(
        self,
        system: System,
        options: BookSimOptions,
        *,
        network_file: str | Path,
    ) -> str:
        self.validate_anynet_runtime(system, options)
        runtime = system.routing_table.metadata["booksim_runtime_routing"]
        bandwidths = sorted({link.bandwidth for link in system.graph.links})
        routing_function = str(runtime["routing_function"])
        lines = [
            "// Generated by Topology Analyzer.",
            "// Backend: anynet_runtime.",
            f"// Requires a BookSim runtime routing function named {routing_function}.",
            f"// system = {system.name}",
            f"// topology_type = {system.topology_type}",
            f"// routing_table = {system.routing_table.name}",
            f"// modeled_link_bandwidths = {','.join(bandwidths)}",
            "topology = anynet;",
            f"routing_function = {routing_function};",
            f"network_file = {_config_path(network_file)};",
            f"anynet_runtime_seed = {int(runtime.get('seed', 0))};",
            f"anynet_runtime_candidates = {int(runtime.get('candidates', 4))};",
            f"anynet_runtime_threshold = {int(runtime.get('adaptive_threshold', 0))};",
        ]
        if routing_function == "ubmesh_apr":
            dimensions = ",".join(
                str(value) for value in system.graph.metadata["dimensions"]
            )
            lines.extend(
                [
                    f"// ubmesh_apr_dimensions = {dimensions};",
                    f"// ubmesh_apr_seed = {int(runtime.get('seed', 0))};",
                    "// ubmesh_apr_vl_policy = tfc_two_virtual_lanes;",
                    "// ubmesh_apr_minimal_candidates = 1;",
                    "// ubmesh_apr_detour_candidates = 1;",
                ]
            )
        lines.extend([*self._common_options(options), ""])
        return "\n".join(lines)

    def generate_stock_fattree(self, system: System, options: BookSimOptions) -> str:
        self.validate_stock_fattree(system)
        params = system.topology_params
        bandwidth = _single_value(
            [link.bandwidth for link in system.graph.links],
            "link bandwidth",
        )
        return "\n".join(
            [
                "// Generated by Topology Analyzer.",
                "// Backend: stock_fattree.",
                "// Uses BookSim native adaptive Fat-tree routing.",
                f"// system = {system.name}",
                f"// routing_table = {system.routing_table.name}",
                f"// modeled_link_bandwidth = {bandwidth}",
                "topology = fattree;",
                f"k = {int(params['radix']) // 2};",
                f"n = {int(params['levels'])};",
                "routing_function = anca;",
                f"traffic = {options.traffic};",
                f"injection_rate = {options.injection_rate};",
                f"packet_size = {options.packet_size};",
                f"injection_rate_uses_flits = {_bool_int(_uses_flit_rate(options.injection_rate_unit))};",
                *self._common_options(options, include_traffic=False),
                "",
            ]
        )

    def generate_stock_mesh(self, system: System, options: BookSimOptions) -> str:
        self.validate_supported(system)
        params = system.topology_params
        bandwidth = _single_value(
            [link.bandwidth for link in system.graph.links],
            "link bandwidth",
        )
        return "\n".join(
            [
                "// Generated by Topology Analyzer.",
                f"// system = {system.name}",
                f"// modeled_link_bandwidth = {bandwidth}",
                "topology = mesh;",
                f"k = {params['x']};",
                "n = 2;",
                "routing_function = dor;",
                "use_noc_latency = 1;",
                f"traffic = {options.traffic};",
                f"injection_rate = {options.injection_rate};",
                f"packet_size = {options.packet_size};",
                f"injection_rate_uses_flits = {_bool_int(_uses_flit_rate(options.injection_rate_unit))};",
                *self._common_options(options, include_traffic=False),
                "",
            ]
        )

    def _common_options(
        self,
        options: BookSimOptions,
        *,
        include_traffic: bool = True,
    ) -> list[str]:
        lines = []
        if include_traffic:
            lines.extend(
                [
                    f"traffic = {options.traffic};",
                    f"injection_rate = {options.injection_rate};",
                    f"packet_size = {options.packet_size};",
                    f"injection_rate_uses_flits = {_bool_int(_uses_flit_rate(options.injection_rate_unit))};",
                ]
            )
        lines.extend(
            [
                "sim_type = latency;",
                f"warmup_periods = {options.warmup_cycles};",
                f"sample_period = {options.sample_cycles};",
                f"max_samples = {options.max_samples};",
                "warmup_thres = -1.0;",
                "acc_warmup_thres = -1.0;",
                "stopping_thres = -1.0;",
                "acc_stopping_thres = -1.0;",
                "latency_thres = -1.0;",
                f"num_vcs = {options.num_vcs};",
                f"vc_buf_size = {options.vc_buffer_size};",
                "vc_allocator = islip;",
                "sw_allocator = islip;",
                "alloc_iters = 1;",
                "credit_delay = 2;",
                "routing_delay = 0;",
                "vc_alloc_delay = 1;",
                "sw_alloc_delay = 1;",
                "st_final_delay = 1;",
                "input_speedup = 1;",
                "output_speedup = 1;",
                "internal_speedup = 1.0;",
                "sim_count = 1;",
                "use_read_write = 0;",
                "wait_for_tail_credit = 1;",
            ]
        )
        return lines

    def validate_supported(self, system: System) -> None:
        if system.topology_type != "mesh2d":
            raise BookSimUnsupportedError(
                f"stock BookSim adapter currently supports mesh2d only, got {system.topology_type}"
            )
        if system.routing_table.name != "mesh_xy":
            raise BookSimUnsupportedError(
                "stock BookSim config generation currently lowers mesh_xy to "
                f"`routing_function = dor`; routing table {system.routing_table.name!r} "
                "needs a custom BookSim routing function or table-driven backend"
            )
        params = system.topology_params
        if int(params["x"]) != int(params["y"]):
            raise BookSimUnsupportedError(
                "stock BookSim mesh uses one k value for both dimensions; "
                f"rectangular mesh2d {params['x']}x{params['y']} needs a custom BookSim topology"
            )
        channel_latency = _single_value(
            [link.latency_cycles for link in system.graph.links],
            "channel latency",
        )
        if channel_latency != 1:
            raise BookSimUnsupportedError(
                "stock BookSim mesh config does not expose a general channel latency; "
                f"modeled latency {channel_latency} needs a custom BookSim topology"
            )
        _single_value([link.bandwidth for link in system.graph.links], "link bandwidth")

    def validate_stock_fattree(self, system: System) -> None:
        if system.topology_type != "fattree":
            raise BookSimUnsupportedError(
                "stock_fattree backend supports fattree systems only, got "
                f"{system.topology_type}"
            )
        if system.routing_table.name != "fattree_anca":
            raise BookSimUnsupportedError(
                "stock_fattree backend currently represents true adaptive ANCA only; "
                f"routing table {system.routing_table.name!r} should use anynet_table"
            )
        runtime = system.routing_table.metadata.get("booksim_runtime_routing")
        if not isinstance(runtime, dict) or runtime.get("routing_function") != "anca":
            raise BookSimUnsupportedError(
                "stock_fattree backend requires fattree_anca runtime routing metadata"
            )
        params = system.topology_params
        if int(params["radix"]) % 2 != 0:
            raise BookSimUnsupportedError("stock_fattree requires even fattree radix")
        channel_latency = _single_value(
            [link.latency_cycles for link in system.graph.links],
            "channel latency",
        )
        if channel_latency != 1:
            raise BookSimUnsupportedError(
                "stock BookSim fattree does not expose per-link channel latency; "
                f"modeled latency {channel_latency} needs anynet_table or a custom topology"
            )
        _single_value([link.bandwidth for link in system.graph.links], "link bandwidth")

    def validate_anynet_runtime(
        self,
        system: System,
        options: BookSimOptions,
    ) -> None:
        runtime = system.routing_table.metadata.get("booksim_runtime_routing")
        if not isinstance(runtime, dict) or not runtime.get("routing_function"):
            raise BookSimUnsupportedError(
                "anynet_runtime backend requires BookSim runtime routing metadata"
            )
        required_vcs = _required_vcs(system)
        if options.num_vcs < required_vcs:
            raise BookSimUnsupportedError(
                f"{system.routing_table.name} requires at least {required_vcs} VCs"
            )


def _single_value(values: list[object], label: str) -> object:
    unique = set(values)
    if len(unique) != 1:
        raise BookSimUnsupportedError(
            f"stock BookSim adapter currently requires homogeneous {label}; got {sorted(unique)}"
        )
    return values[0]


def _uses_flit_rate(unit: str) -> bool:
    return unit == "flits/node/cycle"


def _bool_int(value: bool) -> int:
    return 1 if value else 0


def _normalize_backend(backend: str) -> str:
    normalized = backend.strip().lower().replace("-", "_")
    aliases = {
        "auto": "auto",
        "anynet": "anynet_table",
        "anynet_table": "anynet_table",
        "custom": "anynet_table",
        "custom_anynet": "anynet_table",
        "table": "anynet_table",
        "table_driven": "anynet_table",
        "stock": "stock_mesh",
        "stock_mesh": "stock_mesh",
        "mesh": "stock_mesh",
        "stock_fattree": "stock_fattree",
        "fattree": "stock_fattree",
        "fattree_anca": "stock_fattree",
        "anynet_runtime": "anynet_runtime",
        "runtime": "anynet_runtime",
        "adaptive": "anynet_runtime",
        "ubmesh_apr": "anynet_runtime",
        "ubmesh_apr_runtime": "anynet_runtime",
    }
    if normalized not in aliases:
        raise ValueError(
            "unsupported BookSim backend "
            f"{backend!r}; expected auto, anynet_table, stock_mesh, "
            "stock_fattree, or anynet_runtime"
        )
    return aliases[normalized]


def _required_vcs(system: System) -> int:
    metadata = system.routing_table.metadata
    for key in ("required_vcs", "requires_num_vcs"):
        if key in metadata:
            return int(metadata[key])
    runtime = metadata.get("booksim_runtime_routing")
    if isinstance(runtime, dict) and "required_vcs" in runtime:
        return int(runtime["required_vcs"])
    return 1


def _config_path(path: str | Path) -> str:
    return str(path)
