from __future__ import annotations

from dataclasses import dataclass

from topoanalyzer.model.system import System


class BookSimUnsupportedError(ValueError):
    pass


@dataclass(frozen=True)
class BookSimOptions:
    traffic: str
    injection_rate: float
    injection_rate_unit: str = "packets/node/cycle"
    packet_size: int = 1
    warmup_cycles: int = 10000
    sample_cycles: int = 50000
    max_samples: int = 10
    num_vcs: int = 2
    vc_buffer_size: int = 8
    router_latency: int = 1


class BookSimConfigGenerator:
    def generate(self, system: System, options: BookSimOptions) -> str:
        self.validate_supported(system)
        params = system.topology_params
        bandwidth = _single_value(
            [link.bandwidth for link in system.graph.links],
            "link bandwidth",
        )
        return "\n".join(
            [
                "// Generated by Topology Analyzer.",
                f"// system = {system.name}",
                f"// modeled_link_bandwidth = {bandwidth}",
                "topology = mesh;",
                f"k = {params['x']};",
                "n = 2;",
                "routing_function = dor;",
                "use_noc_latency = 1;",
                f"traffic = {options.traffic};",
                f"injection_rate = {options.injection_rate};",
                f"packet_size = {options.packet_size};",
                f"injection_rate_uses_flits = {_bool_int(_uses_flit_rate(options.injection_rate_unit))};",
                "sim_type = latency;",
                f"warmup_periods = {options.warmup_cycles};",
                f"sample_period = {options.sample_cycles};",
                f"max_samples = {options.max_samples};",
                "warmup_thres = -1.0;",
                "acc_warmup_thres = -1.0;",
                "stopping_thres = -1.0;",
                "acc_stopping_thres = -1.0;",
                "latency_thres = -1.0;",
                f"num_vcs = {options.num_vcs};",
                f"vc_buf_size = {options.vc_buffer_size};",
                "vc_allocator = islip;",
                "sw_allocator = islip;",
                "alloc_iters = 1;",
                "credit_delay = 2;",
                "routing_delay = 0;",
                "vc_alloc_delay = 1;",
                "sw_alloc_delay = 1;",
                "st_final_delay = 1;",
                "input_speedup = 1;",
                "output_speedup = 1;",
                "internal_speedup = 1.0;",
                "sim_count = 1;",
                "use_read_write = 0;",
                "wait_for_tail_credit = 1;",
                "",
            ]
        )

    def validate_supported(self, system: System) -> None:
        if system.topology_type != "mesh2d":
            raise BookSimUnsupportedError(
                f"stock BookSim adapter currently supports mesh2d only, got {system.topology_type}"
            )
        if system.routing_table.name != "mesh_xy":
            raise BookSimUnsupportedError(
                "stock BookSim config generation currently lowers mesh_xy to "
                f"`routing_function = dor`; routing table {system.routing_table.name!r} "
                "needs a custom BookSim routing function or table-driven backend"
            )
        params = system.topology_params
        if int(params["x"]) != int(params["y"]):
            raise BookSimUnsupportedError(
                "stock BookSim mesh uses one k value for both dimensions; "
                f"rectangular mesh2d {params['x']}x{params['y']} needs a custom BookSim topology"
            )
        channel_latency = _single_value(
            [link.latency_cycles for link in system.graph.links],
            "channel latency",
        )
        if channel_latency != 1:
            raise BookSimUnsupportedError(
                "stock BookSim mesh config does not expose a general channel latency; "
                f"modeled latency {channel_latency} needs a custom BookSim topology"
            )
        _single_value([link.bandwidth for link in system.graph.links], "link bandwidth")


def _single_value(values: list[object], label: str) -> object:
    unique = set(values)
    if len(unique) != 1:
        raise BookSimUnsupportedError(
            f"stock BookSim adapter currently requires homogeneous {label}; got {sorted(unique)}"
        )
    return values[0]


def _uses_flit_rate(unit: str) -> bool:
    return unit == "flits/node/cycle"


def _bool_int(value: bool) -> int:
    return 1 if value else 0
